### ISSUE TITLE
prout prout uwu

### ISSUE THREAD

**Issue by fritzhaxx** [Zeldown/ConfigAnnotation#1]
salus j'utilise commens sa dan mon chet paladiume (pur keybinde=à))

**Comment by fritzhaxx** [comment]
dailleurs pk sa fais lagueN?NN

**Comment by Zeldown** [comment]
Bonsoir, il suffit de savoir lire un readme 👀

**Comment by fritzhaxx** [comment]
ok merci ça fonctionne
